### ISSUE TITLE
SAML2.Logging.LoggerProvider null reference exception

### ISSUE THREAD

**Issue by egontier** [i8beef/SAML2#33]
Hello,

I'm trying to put SAML2 into my project and sometimes i've a problem with the logger provider. I didn't find any resource about how to configure a logger into my web.config to avoid this problem.
I've found that maybe it could be a malformed metadata file, but in my case i d'ont thing its the problem because i manage to make it work with my visual studio.

Here is the stack trace :
`
[NullReferenceException: Object reference not set to an instance of an object.]    SAML2.Logging.LoggerProvider.LoggerFor(Type type) +26    SAML2.Config.IdentityProviderCollection.ParseFile(String file) +419    SAML2.Config.IdentityProviderCollection.Refresh() +674    SAML2.Config.Saml2Config.GetConfig() +80    SAML2.Logging.LoggerProvider..cctor() +25  [TypeInitializationException: The type initializer for 'SAML2.Logging.LoggerProvider' threw an exception.]    SAML2.Logging.LoggerProvider.LoggerFor(Type type) +0    SAML2.Protocol.AbstractEndpointHandler..cctor() +44  [TypeInitializationException: The type initializer for 'SAML2.Protocol.AbstractEndpointHandler' threw an exception.]    SAML2.Protocol.Saml20AbstractEndpointHandler.ProcessRequest(HttpContext context) +71    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +341    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69`
--

I've read this https://github.com/i8beef/SAML2/issues/16 but it didn't help :(

Thank you for your helps and merry christmas to all of you !

Eric

**Comment by i8beef** [comment]
https://github.com/i8beef/SAML2/wiki/Logging-Element

What does your logging configuration element look like here?

**Comment by egontier** [comment]
Hello i8beef !
Thank you for your answer, and sorry for the delay of mine :)
I've seen in the documentation that the logging element is optionnal.
So i don't have any logging configuration element ...
This could be a NoLogging provider problem ?
I will try to set up a logging provider to give it a try

Thank you for your answer

**Comment by i8beef** [comment]
Hm actually looking at your stack trace, it looks like you might be seeing an issue with where it refreshes the IDP metadata. I remember theres a condition where an error in that part during startup tries to log something but the logger isn't yet setup... Do you have your IDP metadata files in place?

**Comment by egontier** [comment]
Hello ! 
Yes i have my metadata file stored in the app_data. Everything works fine on my visual studio that way but i try it on a developpement server, this error hide the real problem :(
It might be a dumb question but i didn't manage to understand where to configure the path to the metadata xml file, but well it works on my developpement environnement so its seems to be magical ! Can i explicitly set it up in my web.config ?

I tried to set up the log4net logger without success apprently because i still have the error... is there a sample app somewhere where i could get inspired ?

Thank you again for your help

**Comment by i8beef** [comment]
Actually, that should have been fixed back in https://github.com/i8beef/SAML2/issues/16, and the stack trace up there points at maybe you are running an old version? Sam2Config.GetConfig() hasn't existed for a while.

**Comment by egontier** [comment]
Hello !
Well that's not the problem, i've been trying to fix this for a long time now... I've updated the lib with the last version and i still have the same problem.

```
An unhandled exception was generated during the execution of the  current web request. Information regarding the origin and location of the  exception can be identified using the exception stack trace below.
--

NullReferenceException: Object reference not set to an instance of an object.]    SAML2.Logging.LoggerProvider.LoggerFor(Type type) +26    SAML2.Config.IdentityProviderCollection.ParseFile(String file) +819    SAML2.Config.IdentityProviderCollection.Refresh() +800    SAML2.Config.Saml2Config.InitFromConfigFile() +71    SAML2.Config.Saml2Config.get_Current() +18    SAML2.Logging.LoggerProvider..cctor() +25  [TypeInitializationException: The type initializer for 'SAML2.Logging.LoggerProvider' threw an exception.]    SAML2.Logging.LoggerProvider.LoggerFor(Type type) +0    SAML2.Protocol.AbstractEndpointHandler..cctor() +44  [TypeInitializationException: The type initializer for 'SAML2.Protocol.AbstractEndpointHandler' threw an exception.]    SAML2.Protocol.Saml20AbstractEndpointHandler.ProcessRequest(HttpContext context) +71    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +341    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
--
```

It's maybe an OS problem because i've got this error on a windows server 2008 R2 but not on a win server 2012 R2, this is very strange ...
Since we know it's a problem of metadata file parsing, what can be the difference between those OS ? A cryptographic problem ? Do you have any clue ?
I'm still interesting in setting up à logger, is there a sample app somewhere with a logger example ?

Thanks you for your time

Eric

**Comment by egontier** [comment]
Well, i've found the problem. I had others xml files in my app_data folder so i created a dedicated folder with the metatadata isolated and it works fine.
Anyway your fix #16 does not work !
Thank you for your answers, and if there is somewhere an example of logger configuration i would apreciate :)
Have a good day !

**Comment by i8beef** [comment]
Ah, yes, sorry that's probably not documented. It assumes that directory is ONLY for XML metadata.

For the logging setup you have to first choose a logging provider, like this one: https://github.com/i8beef/SAML2.Logging.Log4Net/wiki

Basically you install one of the logging modules and then just set the config to use it with that line. There is a log4net provider, and a CommonLogging one from way back, though none of those have seen any updates since their inception (not REALLY needed). If you're using NLog or Microsoft.Extensions.Logging you could write your own integration with that fairly easily too, just use that repo as a basic template and implement against the different library, then register it in the SAML2 config like above.

**Comment by nreddipalle** [comment]
@i8beef I am getting the same exception as above with the current master branch.. I have only one metadata file in my folder.. just wondering what is the best way to debug this if I want to call it from a console app and test it out>>
